/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jahazielexamen;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jahaziel
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tab_prin = new javax.swing.JTabbedPane();
        jPanel34 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel39 = new javax.swing.JPanel();
        jLabel106 = new javax.swing.JLabel();
        nombre_tf = new javax.swing.JTextField();
        jLabel107 = new javax.swing.JLabel();
        edad_tf = new javax.swing.JTextField();
        jLabel108 = new javax.swing.JLabel();
        ID_tf = new javax.swing.JTextField();
        jLabel109 = new javax.swing.JLabel();
        contraseña_tf = new javax.swing.JTextField();
        jLabel110 = new javax.swing.JLabel();
        Idboleto_tf = new javax.swing.JTextField();
        jLabel111 = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        t_p = new javax.swing.JTabbedPane();
        jPanel40 = new javax.swing.JPanel();
        jLabel112 = new javax.swing.JLabel();
        empleo_tf = new javax.swing.JTextField();
        jPanel41 = new javax.swing.JPanel();
        jLabel113 = new javax.swing.JLabel();
        carrera_tf = new javax.swing.JTextField();
        jPanel42 = new javax.swing.JPanel();
        jLabel114 = new javax.swing.JLabel();
        partido_cb = new javax.swing.JComboBox<>();
        depaCB = new javax.swing.JComboBox<>();
        jLabel41 = new javax.swing.JLabel();
        Dinero_tf = new javax.swing.JTextField();
        jPanel35 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel43 = new javax.swing.JPanel();
        jLabel115 = new javax.swing.JLabel();
        nombre_tf1 = new javax.swing.JTextField();
        jLabel116 = new javax.swing.JLabel();
        edad_tf1 = new javax.swing.JTextField();
        jLabel117 = new javax.swing.JLabel();
        ID_tf1 = new javax.swing.JTextField();
        jLabel118 = new javax.swing.JLabel();
        contraseña_tf1 = new javax.swing.JTextField();
        jLabel119 = new javax.swing.JLabel();
        Idboleto_tf1 = new javax.swing.JTextField();
        jLabel120 = new javax.swing.JLabel();
        Guiardia = new javax.swing.JButton();
        t_p1 = new javax.swing.JTabbedPane();
        jPanel44 = new javax.swing.JPanel();
        jLabel121 = new javax.swing.JLabel();
        empleo_tf1 = new javax.swing.JTextField();
        jPanel45 = new javax.swing.JPanel();
        jLabel122 = new javax.swing.JLabel();
        carrera_tf1 = new javax.swing.JTextField();
        jPanel46 = new javax.swing.JPanel();
        jLabel123 = new javax.swing.JLabel();
        partido_cb1 = new javax.swing.JComboBox<>();
        depaCB1 = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        Dinero_tf1 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        GuardarPCB = new javax.swing.JComboBox<>();
        jPanel36 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        per_cb = new javax.swing.JComboBox<>();
        Eliminar_BT = new javax.swing.JButton();
        jPanel37 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        personasCB = new javax.swing.JComboBox<>();
        jLabel42 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jPanel38 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        perVenta = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel47 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tab_prin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tab_prinStateChanged(evt);
            }
        });

        jLabel106.setText("Nombre");

        jLabel107.setText("Edad");

        jLabel108.setText("ID");

        jLabel109.setText("Contraseña");

        jLabel110.setText("ID Boleto");

        jLabel111.setText("Departamento");

        agregar.setText("Agregar");
        agregar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                agregarStateChanged(evt);
            }
        });
        agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarMouseClicked(evt);
            }
        });
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        jLabel112.setText("Empleo:");

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel40Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel112)
                .addGap(18, 18, 18)
                .addComponent(empleo_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel40Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel112)
                    .addComponent(empleo_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        t_p.addTab("Empleados", jPanel40);

        jLabel113.setText("Carrera:");

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel41Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel113)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(carrera_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel41Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel113)
                    .addComponent(carrera_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        t_p.addTab("Estudiantes", jPanel41);

        jLabel114.setText("Partido");

        partido_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nacional", "liberal", "Libre" }));

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel114, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(partido_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel114)
                    .addComponent(partido_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        t_p.addTab("Politico", jPanel42);

        depaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atlantida", "Choluteca", "Colon", "Comayagua", "Copan", "Cortez", "El Paraiso", "Francisco Morazan", "Gracias A Dios", "Intibuca", "Islas De La Bahia", "La Paz", "Lempira", "Ocotepeque", "Olancho", "Santa Barbara", "Yoro" }));

        jLabel41.setText("Dinero");

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel39Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel106)
                            .addComponent(jLabel107)
                            .addComponent(jLabel108))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ID_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edad_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel39Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel39Layout.createSequentialGroup()
                                .addComponent(jLabel109)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(contraseña_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel39Layout.createSequentialGroup()
                                .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel110)
                                    .addComponent(jLabel111)
                                    .addComponent(jLabel41))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Idboleto_tf)
                                    .addComponent(depaCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Dinero_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(t_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel39Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel106, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel107)
                            .addComponent(edad_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel108)
                            .addComponent(ID_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel109)
                            .addComponent(contraseña_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel110)
                            .addComponent(Idboleto_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel39Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(t_p, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel111)
                    .addComponent(depaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(Dinero_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(agregar)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Persona", jPanel39);

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        tab_prin.addTab("Agregar", jPanel34);

        jLabel115.setText("Nombre");

        jLabel116.setText("Edad");

        jLabel117.setText("ID");

        jLabel118.setText("Contraseña");

        jLabel119.setText("ID Boleto");

        jLabel120.setText("Departamento");

        Guiardia.setText("Guardar");
        Guiardia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                GuiardiaStateChanged(evt);
            }
        });
        Guiardia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuiardiaMouseClicked(evt);
            }
        });
        Guiardia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuiardiaActionPerformed(evt);
            }
        });

        jLabel121.setText("Empleo:");

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel121)
                .addGap(18, 18, 18)
                .addComponent(empleo_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel121)
                    .addComponent(empleo_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        t_p1.addTab("Empleados", jPanel44);

        jLabel122.setText("Carrera:");

        javax.swing.GroupLayout jPanel45Layout = new javax.swing.GroupLayout(jPanel45);
        jPanel45.setLayout(jPanel45Layout);
        jPanel45Layout.setHorizontalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel45Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel122)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(carrera_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel45Layout.setVerticalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel45Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel122)
                    .addComponent(carrera_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        t_p1.addTab("Estudiantes", jPanel45);

        jLabel123.setText("Partido");

        partido_cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nacional", "liberal", "Libre" }));

        javax.swing.GroupLayout jPanel46Layout = new javax.swing.GroupLayout(jPanel46);
        jPanel46.setLayout(jPanel46Layout);
        jPanel46Layout.setHorizontalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel46Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel123, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(partido_cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel46Layout.setVerticalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel46Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel123)
                    .addComponent(partido_cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        t_p1.addTab("Politico", jPanel46);

        depaCB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atlantida", "Choluteca", "Colon", "Comayagua", "Copan", "Cortez", "El Paraiso", "Francisco Morazan", "Gracias A Dios", "Intibuca", "Islas De La Bahia", "La Paz", "Lempira", "Ocotepeque", "Olancho", "Santa Barbara", "Yoro" }));

        jLabel43.setText("Dinero");

        jLabel44.setText("Personas");

        GuardarPCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                GuardarPCBItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel43Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Guiardia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel43Layout.createSequentialGroup()
                        .addComponent(jLabel117)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ID_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel43Layout.createSequentialGroup()
                        .addComponent(jLabel118)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(contraseña_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel43Layout.createSequentialGroup()
                        .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel119)
                            .addComponent(jLabel120)
                            .addComponent(jLabel43))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Idboleto_tf1)
                            .addComponent(depaCB1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Dinero_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel43Layout.createSequentialGroup()
                        .addComponent(jLabel116)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edad_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel43Layout.createSequentialGroup()
                        .addComponent(jLabel115)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nombre_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72)
                .addComponent(t_p1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel43Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel44)
                .addGap(18, 18, 18)
                .addComponent(GuardarPCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel43Layout.createSequentialGroup()
                .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel43Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel116)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel117)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel118)
                            .addComponent(contraseña_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel119)
                            .addComponent(Idboleto_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel43Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(GuardarPCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel115, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(edad_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ID_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel43Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(t_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel120)
                    .addComponent(depaCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(Dinero_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(Guiardia)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Persona", jPanel43);

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jTabbedPane3)
                .addGap(19, 19, 19))
        );

        tab_prin.addTab("Modificar", jPanel35);

        jLabel45.setText("Personas");

        per_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                per_cbItemStateChanged(evt);
            }
        });
        per_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                per_cbActionPerformed(evt);
            }
        });

        Eliminar_BT.setText("Eliminar");
        Eliminar_BT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Eliminar_BTMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel36Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel45)
                        .addGap(18, 18, 18)
                        .addComponent(per_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel36Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(Eliminar_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(459, Short.MAX_VALUE))
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(per_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(Eliminar_BT, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(422, Short.MAX_VALUE))
        );

        tab_prin.addTab("Eliminar", jPanel36);

        personasCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                personasCBItemStateChanged(evt);
            }
        });

        jLabel42.setText("Personas");

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla1);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addGap(18, 18, 18)
                        .addComponent(personasCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personasCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addGap(80, 80, 80)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
            .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel37Layout.createSequentialGroup()
                    .addGap(0, 15, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 15, Short.MAX_VALUE)))
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
            .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel37Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        tab_prin.addTab("Listar", jPanel37);

        jLabel46.setText("Personas");

        perVenta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                perVentaItemStateChanged(evt);
            }
        });
        perVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perVentaActionPerformed(evt);
            }
        });

        jRadioButton1.setText("350 LP");

        jLabel47.setText("Elija Premio");

        jRadioButton2.setText("10,000 LP");

        jRadioButton3.setText("100,000 LP");

        jRadioButton4.setText("1,000,000 LP");

        jButton1.setText("COMPRAR BOLETO");

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addGroup(jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel38Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel46)
                        .addGap(18, 18, 18)
                        .addComponent(perVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel38Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47)
                            .addGroup(jPanel38Layout.createSequentialGroup()
                                .addGroup(jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel38Layout.createSequentialGroup()
                                        .addComponent(jRadioButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton2)))
                                .addGap(31, 31, 31)
                                .addComponent(jRadioButton3)
                                .addGap(31, 31, 31)
                                .addComponent(jRadioButton4)))))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(perVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jLabel47)
                .addGap(18, 18, 18)
                .addGroup(jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addGap(88, 88, 88)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        tab_prin.addTab("Venta", jPanel38);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
        );

        tab_prin.addTab("rifa", jPanel14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab_prin, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab_prin)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void agregarStateChanged(javax.swing.event.ChangeEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void agregarMouseClicked(java.awt.event.MouseEvent evt) {                                     
        float Dinero;
        int edad;
        String nombre, ID, IDBoleto, Departamento, empleo, carrera, partido;
        if (t_p.getSelectedIndex() == 0) {
            try {

                ID = ID_tf.getText();
                nombre = nombre_tf.getText();
                edad = Integer.parseInt(edad_tf.getText());
                Dinero = Float.parseFloat(Dinero_tf.getText());
                IDBoleto = Idboleto_tf.getText();
                Departamento = depaCB.getItemAt(depaCB.getSelectedIndex());
                empleo = empleo_tf.getText();

                lista.add(new Empleados(empleo, nombre, ID, IDBoleto, Departamento, Dinero, edad));
                JOptionPane.showMessageDialog(this, "El contacto fue agregado exitosamente");

                //-----------------resetear controles ----------------------------------------------------------------------
                nombre_tf.setText("");
                ID_tf.setText("");
                Dinero_tf.setText("");
                edad_tf.setText("");
                Idboleto_tf.setText("");
                depaCB.setSelectedIndex(0);
                empleo_tf.setText("");

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Ocurrio un error y no se guardaron los datos");
            }
        }
        
        if (t_p.getSelectedIndex() == 1) {//estudiantes
            try {

                ID = ID_tf.getText();
                nombre = nombre_tf.getText();
                edad = Integer.parseInt(edad_tf.getText());
                Dinero = Float.parseFloat(Dinero_tf.getText());
                IDBoleto = Idboleto_tf.getText();
                Departamento = depaCB.getItemAt(depaCB.getSelectedIndex());
                carrera = carrera_tf.getText();
                lista.add(new Estudiantes(carrera, nombre, ID, IDBoleto, Departamento, Dinero, edad));
                JOptionPane.showMessageDialog(this, "El contacto fue agregado exitosamente");

                //-----------------resetear controles ----------------------------------------------------------------------
                
                nombre_tf.setText("");
                ID_tf.setText("");
                Dinero_tf.setText("");
                edad_tf.setText("");
                Idboleto_tf.setText("");
                depaCB.setSelectedIndex(0);
                carrera_tf.setText("");
                
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Ocurrio un error y no se guardaron los datos");
            }
        }
        
        if (t_p.getSelectedIndex() == 2) {// Politico
            try {

                ID = ID_tf.getText();
                nombre = nombre_tf.getText();
                edad = Integer.parseInt(edad_tf.getText());
                Dinero = Float.parseFloat(Dinero_tf.getText());
                IDBoleto = Idboleto_tf.getText();
                Departamento = depaCB.getItemAt(depaCB.getSelectedIndex());
                partido = partido_cb.getItemAt(partido_cb.getSelectedIndex());
                lista.add(new Politico(partido, nombre, ID, IDBoleto, Departamento, Dinero, edad));
                JOptionPane.showMessageDialog(this, "El contacto fue agregado exitosamente");

                //-----------------resetear controles ----------------------------------------------------------------------
                
                nombre_tf.setText("");
                ID_tf.setText("");
                Dinero_tf.setText("");
                edad_tf.setText("");
                Idboleto_tf.setText("");
                depaCB.setSelectedIndex(0);
                partido_cb.setSelectedIndex(0);
                
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Ocurrio un error y no se guardaron los datos");
            }
        }
    }                                    

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void personasCBItemStateChanged(java.awt.event.ItemEvent evt) {                                            
        
        if (evt.getStateChange() == 2) {//va a haber dos eventos contaer y extra
            Personas s = (Personas) personasCB.getSelectedItem();

            Object[] newrow = {// por los distintos tipos arreglo de object
                s.getNombre(),
                s.getEdad(), s.getID()

            };

            DefaultTableModel modelo = (DefaultTableModel) tabla1.getModel();
            modelo.addRow(newrow);
            tabla1.setModel(modelo);

            //tf_edad_maxima.setText(Maxima_edad());
        }
    }                                           

    private void tab_prinStateChanged(javax.swing.event.ChangeEvent evt) {                                      
        
        if (tab_prin.getSelectedIndex() == 3) {
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            for (Personas temp : lista) {
                    modelo.addElement(temp);
                    
                personasCB.setModel(modelo);
            }
        }

        if (tab_prin.getSelectedIndex() == 1) {
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            for (Personas temp : lista) {
                    modelo.addElement(temp);
                    
              GuardarPCB.setModel(modelo);
            }
        }
        
        if (tab_prin.getSelectedIndex() == 2) {
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            for (Personas temp : lista) {
                    modelo.addElement(temp);
                    
              per_cb.setModel(modelo);
            }
        }
        
        if (tab_prin.getSelectedIndex() == 4) {
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            for (Personas temp : lista) {
                    modelo.addElement(temp);
                    
              perVenta.setModel(modelo);
            }
        }
        
    }                                     

    private void GuiardiaStateChanged(javax.swing.event.ChangeEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void GuiardiaMouseClicked(java.awt.event.MouseEvent evt) {                                      
       //Modification
        float Dinero;
        int edad;
        String nombre, ID, IDBoleto, Departamento, empleo, carrera, partido;
        if (t_p.getSelectedIndex() == 0) {
            try {

                ID = ID_tf1.getText();
                nombre = nombre_tf1.getText();
                edad = Integer.parseInt(edad_tf1.getText());
                Dinero = Float.parseFloat(Dinero_tf1.getText());
                IDBoleto = Idboleto_tf1.getText();
                Departamento = depaCB1.getItemAt(depaCB1.getSelectedIndex());
                empleo = empleo_tf1.getText();
                
                lista.get(GuardarPCB.getSelectedIndex()).setNombre(nombre);
                lista.get(GuardarPCB.getSelectedIndex()).setID(ID);
                lista.get(GuardarPCB.getSelectedIndex()).setEdad(edad);
                lista.get(GuardarPCB.getSelectedIndex()).setIDBoleto(IDBoleto);
                lista.get(GuardarPCB.getSelectedIndex()).setDepartamento(Departamento);
                ((Empleados)lista.get(GuardarPCB.getSelectedIndex())).setEmpleo(empleo);

                JOptionPane.showMessageDialog(this, "El contacto fue Modificado exitosamente");

                //-----------------resetear controles ----------------------------------------------------------------------
                nombre_tf1.setText("");
                ID_tf1.setText("");
                Dinero_tf1.setText("");
                edad_tf1.setText("");
                Idboleto_tf1.setText("");
                depaCB1.setSelectedIndex(0);
                empleo_tf1.setText("");

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Ocurrio un error y no se modificaron los datos");
            }
        }
        
        if (t_p.getSelectedIndex() == 1) {//estudiantes
            try {

                ID = ID_tf.getText();
                nombre = nombre_tf1.getText();
                edad = Integer.parseInt(edad_tf1.getText());
                Dinero = Float.parseFloat(Dinero_tf1.getText());
                IDBoleto = Idboleto_tf1.getText();
                Departamento = depaCB1.getItemAt(depaCB1.getSelectedIndex());
                carrera = carrera_tf1.getText();
                lista.add(new Estudiantes(carrera, nombre, ID, IDBoleto, Departamento, Dinero, edad));
                JOptionPane.showMessageDialog(this, "El contacto fue modificado exitosamente");
                
                lista.get(GuardarPCB.getSelectedIndex()).setNombre(nombre);
                lista.get(GuardarPCB.getSelectedIndex()).setID(ID);
                lista.get(GuardarPCB.getSelectedIndex()).setEdad(edad);
                lista.get(GuardarPCB.getSelectedIndex()).setIDBoleto(IDBoleto);
                lista.get(GuardarPCB.getSelectedIndex()).setDepartamento(Departamento);
                ((Estudiantes)lista.get(GuardarPCB.getSelectedIndex())).setCarrera(carrera);

                //-----------------resetear controles ----------------------------------------------------------------------
                
                nombre_tf1.setText("");
                ID_tf1.setText("");
                Dinero_tf1.setText("");
                edad_tf1.setText("");
                Idboleto_tf1.setText("");
                depaCB1.setSelectedIndex(0);
                carrera_tf1.setText("");
                
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Ocurrio un error y no se modificaron los datos");
            }
        }
        
        if (t_p.getSelectedIndex() == 2) {// Politico
            try {

                ID = ID_tf1.getText();
                nombre = nombre_tf1.getText();
                edad = Integer.parseInt(edad_tf1.getText());
                Dinero = Float.parseFloat(Dinero_tf1.getText());
                IDBoleto = Idboleto_tf1.getText();
                Departamento = depaCB1.getItemAt(depaCB1.getSelectedIndex());
                partido = partido_cb1.getItemAt(partido_cb1.getSelectedIndex());
                
                lista.get(GuardarPCB.getSelectedIndex()).setNombre(nombre);
                lista.get(GuardarPCB.getSelectedIndex()).setID(ID);
                lista.get(GuardarPCB.getSelectedIndex()).setEdad(edad);
                lista.get(GuardarPCB.getSelectedIndex()).setIDBoleto(IDBoleto);
                lista.get(GuardarPCB.getSelectedIndex()).setDepartamento(Departamento);
                ((Politico)lista.get(GuardarPCB.getSelectedIndex())).setPartido(partido);

                JOptionPane.showMessageDialog(this, "El contacto fue modificado exitosamente");

                //-----------------resetear controles ----------------------------------------------------------------------
                
                nombre_tf1.setText("");
                ID_tf1.setText("");
                Dinero_tf1.setText("");
                edad_tf1.setText("");
                Idboleto_tf1.setText("");
                depaCB1.setSelectedIndex(0);
                partido_cb1.setSelectedIndex(0);
                
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Ocurrio un error y no se guardaron los datos");
            }
        }
       
       
    }                                     

    private void GuiardiaActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void GuardarPCBItemStateChanged(java.awt.event.ItemEvent evt) {                                            
       // Modificar COmbo
        
        
        

            //tf_edad_maxima.setText(Maxima_edad());
               
    }                                           

    private void per_cbItemStateChanged(java.awt.event.ItemEvent evt) {                                        
        
        
    }                                       

    private void per_cbActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void Eliminar_BTMouseClicked(java.awt.event.MouseEvent evt) {                                         
        
          lista.remove(lista.get(per_cb.getSelectedIndex()));
 
    }                                        

    private void perVentaItemStateChanged(java.awt.event.ItemEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void perVentaActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField Dinero_tf;
    private javax.swing.JTextField Dinero_tf1;
    private javax.swing.JButton Eliminar_BT;
    private javax.swing.JButton Guard;
    private javax.swing.JButton Guard1;
    private javax.swing.JButton Guard2;
    private javax.swing.JButton Guard3;
    private javax.swing.JComboBox<String> GuardarPCB;
    private javax.swing.JButton Guiardia;
    private javax.swing.JTextField ID_tf;
    private javax.swing.JTextField ID_tf1;
    private javax.swing.JTextField Idboleto_tf;
    private javax.swing.JTextField Idboleto_tf1;
    private javax.swing.JTabbedPane Tb_person;
    private javax.swing.JTabbedPane Tb_person1;
    private javax.swing.JTabbedPane Tb_person2;
    private javax.swing.JTabbedPane Tb_person3;
    private javax.swing.JButton agregar;
    private javax.swing.JTextField altura_tf;
    private javax.swing.JTextField altura_tf1;
    private javax.swing.JTextField altura_tf2;
    private javax.swing.JTextField altura_tf3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField carrera_tf;
    private javax.swing.JTextField carrera_tf1;
    private javax.swing.JTextField contraseña_tf;
    private javax.swing.JTextField contraseña_tf1;
    private javax.swing.JComboBox<String> depaCB;
    private javax.swing.JComboBox<String> depaCB1;
    private javax.swing.JTextField edad_tf;
    private javax.swing.JTextField edad_tf1;
    private javax.swing.JTextField empleo_tf;
    private javax.swing.JTextField empleo_tf1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField nombre_tf;
    private javax.swing.JTextField nombre_tf1;
    private javax.swing.JComboBox<String> partido_cb;
    private javax.swing.JComboBox<String> partido_cb1;
    private javax.swing.JComboBox<String> perVenta;
    private javax.swing.JComboBox<String> per_cb;
    private javax.swing.JComboBox<String> personasCB;
    private javax.swing.JTextField peso_tf;
    private javax.swing.JTextField peso_tf1;
    private javax.swing.JTextField peso_tf2;
    private javax.swing.JTextField peso_tf3;
    private javax.swing.JComboBox<String> rolcb;
    private javax.swing.JComboBox<String> rolcb1;
    private javax.swing.JComboBox<String> rolcb2;
    private javax.swing.JComboBox<String> rolcb3;
    private javax.swing.JTabbedPane t_p;
    private javax.swing.JTabbedPane t_p1;
    private javax.swing.JTabbedPane tab_prin;
    private javax.swing.JTabbedPane tab_principal;
    private javax.swing.JTabbedPane tab_principal1;
    private javax.swing.JTabbedPane tab_principal2;
    private javax.swing.JTabbedPane tab_principal3;
    private javax.swing.JTabbedPane tab_secu;
    private javax.swing.JTabbedPane tab_secu1;
    private javax.swing.JTabbedPane tab_secu2;
    private javax.swing.JTabbedPane tab_secu3;
    private javax.swing.JTable tabla1;
    private javax.swing.JTextField tf_civil;
    private javax.swing.JTextField tf_civil1;
    private javax.swing.JTextField tf_civil2;
    private javax.swing.JTextField tf_civil3;
    private javax.swing.JTextField tf_edad;
    private javax.swing.JTextField tf_edad1;
    private javax.swing.JTextField tf_edad2;
    private javax.swing.JTextField tf_edad3;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_id1;
    private javax.swing.JTextField tf_id2;
    private javax.swing.JTextField tf_id3;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombre1;
    private javax.swing.JTextField tf_nombre2;
    private javax.swing.JTextField tf_nombre3;
    private javax.swing.JTextField tf_pass;
    private javax.swing.JTextField tf_pass1;
    private javax.swing.JTextField tf_pass2;
    private javax.swing.JTextField tf_pass3;
    private javax.swing.JTextField tf_sexo;
    private javax.swing.JTextField tf_sexo1;
    private javax.swing.JTextField tf_sexo2;
    private javax.swing.JTextField tf_sexo3;
    private javax.swing.JTextField trabajo_tf;
    private javax.swing.JTextField trabajo_tf1;
    private javax.swing.JTextField trabajo_tf2;
    private javax.swing.JTextField trabajo_tf3;
    // End of variables declaration                   
ArrayList <Personas> lista = new ArrayList();

static public int [][] llenar (int tam, int [][] x, int num){
    for (int i = 0; i < x.length; i++) {
        for (int j = 0; j < x.length; j++) {
            if (j==0){
                x[i][j]= num;
            }else if (i==j){
                x[i][j] = num;
            } else{
                x[i][j] = 0;
            }
            
            
        }
    }
    
    return x;
}

static int [][] pascal(int [][] x, int num){
    for (int i = 0; i < x.length; i++) {
        for (int j = 0; j < x.length; j++) {
            x[i+1][j+1]= x[i][j]+x [i][j+1];
        }
    }
    return x;
}

static int [][] random (int [][] x, int num){
    Random r = new Random();
    
    int a,b;
    while(num!=0){
    a = 1 + r.nextInt(x.length-1);
    b = 1+ r.nextInt(x.length-1);
    for (int i = 0; i < x.length-1; i++) {
        for (int j = 0; j < x.length-1; j++) {
            num = x[a][b];
        }
    }
    }
   return num;
}


}
